name: FollowMe
version: '${project.version}'
main: mov.naspen.naspanopticam.NasPanoptiCam
api-version: '1.20'
softdepend: [Essentials]
commands:
    naspanopticam:
        description: NasPanoptiCam command
        permission: naspanopticam.set
        default: op
        usage: /naspanopticam set
