name: NasPanoptiCam
version: '${project.version}'
main: mov.naspen.naspanopticam.NasPanoptiCam
api-version: '1.20'
softdepend: [Essentials]
depend: [LuckPerms]
commands:
    naspanopticam:
        description: Manage the NasPanoptiCam plugin
        usage: /naspanopticam <args>
    dontfollowme:
        description: Prevents the player from being followed by the follower account
        usage: /dontfollowme
    followme:
        description: Allows the player to be followed by the follower account
        usage: /followme

permissions:
    aspanopticam.add:
        description: ability to use the add sub-command
        default: op
    naspanopticam.add.location:
        description: ability to use the add location sub-sub-command
        default: op
    naspanopticam.reload:
        description: ability to use the reload sub-command
        default: op
    naspanopticam.dump:
        description: ability to use the dumpsessions  sub-command
        default: op
