name: FollowMe
version: '${project.version}'
main: mov.naspen.followme.FollowMe
api-version: '1.20'
softdepend: [Essentials]
commands:
    followme:
        description: FollowMe command
        permission: followme.set
        default: op
        usage: /followme set
